import { test, expect } from '@playwright/test';
test('두 비교 대상과 상세·지표·조건·월별 표 상태를 독립적으로 유지한다', async ({page}) => {
 await page.goto('/');
 await page.locator('.input-mode').getByRole('button',{name:'예시 정보로 시작하기'}).click();
 await page.getByRole('button',{name:'추천 결과 확인하기'}).click();
 await expect(page.locator('.scenario-line')).toHaveCount(2);
 const a=page.getByRole('combobox',{name:'비교할 시나리오 A',exact:true});
 const b=page.getByRole('combobox',{name:'비교할 시나리오 B',exact:true});
 await expect(a.locator('option[value="balance"]')).toBeDisabled();
 await b.selectOption('maximum-use');
 await page.getByRole('radio',{name:'남은 대출잔액',exact:true}).click();
 const end=await page.locator('.timeline-chart').getAttribute('data-end');
 await page.getByRole('radio',{name:'6개월',exact:true}).click();
 await page.getByRole('checkbox',{name:'초봉 20% 감소',exact:true}).check();
 await expect(page.locator('.chart-condition')).toContainText('변경 조건');
 const ticks=await page.locator('.timeline-chart > text').allTextContents();
 await page.getByRole('radio',{name:'기본 조건',exact:true}).click();
 const baseTicks=await page.locator('.timeline-chart > text').allTextContents();
 expect(baseTicks.slice(0,5)).toEqual(ticks.slice(0,5));
 await expect(page.locator('.timeline-chart')).toHaveAttribute('data-end',end);
 await expect(page.getByRole('slider')).toHaveCount(0);
 await page.locator('.timeline-chart').press('ArrowRight');
 await expect(page.locator('#timeline-readout')).toContainText('6개월 후');
 const paths=await page.locator('.scenario-line').evaluateAll(els=>els.map(el=>el.getAttribute('d')));
 await page.getByRole('radio',{name:/최소대출안 현재/}).check();
 expect(await page.locator('.scenario-line').evaluateAll(els=>els.map(el=>el.getAttribute('d')))).toEqual(paths);
 await page.getByRole('button',{name:'초기화',exact:true}).click();
 await expect(b).toHaveValue('maximum-use');
 await expect(page.getByRole('radio',{name:'남은 대출잔액',exact:true})).toHaveAttribute('aria-checked','true');
 await page.getByText('표로 보기',{exact:true}).click();
 await expect(page.locator('.timeline-table tbody tr')).toHaveCount(Number(end)+1);
 for(const width of [1440,720,360]) {
  await page.setViewportSize({width,height:900});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
 }
});
test('조회 클릭 후 포인터가 움직여도 시점이 고정되고 사용자 학기 금액을 저장한다',async({page})=>{
 await page.goto('/');
 await page.locator('.input-mode').getByRole('button',{name:'예시 정보로 시작하기'}).click();
 await page.getByRole('button',{name:'추천 결과 확인하기'}).click();
 const chart=page.locator('.timeline-chart');
 await chart.click();
 const selected=await page.locator('#timeline-readout').textContent();
 const box=await chart.boundingBox();
 await page.mouse.move(box.x+box.width*.8,box.y+box.height*.5);
 await expect(page.locator('#timeline-readout')).toHaveText(selected);
 await page.getByRole('button',{name:'+ 내 시나리오 추가',exact:true}).click();
 await page.getByRole('spinbutton',{name:'학기당 생활비 대출액',exact:true}).fill('123');
 await page.getByRole('button',{name:'시나리오 추가',exact:true}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await expect(page.locator('#custom-error')).toContainText('125만 원');
 await page.getByRole('spinbutton',{name:'학기당 생활비 대출액',exact:true}).fill('100');
 await page.getByRole('checkbox',{name:'학기별로 다르게 설정'}).check();
 await page.getByRole('spinbutton',{name:'1학기 생활비 대출액',exact:true}).fill('125');
 await expect(page.locator('#custom-amount-preview')).toContainText('825만 원');
 await page.getByRole('button',{name:'시나리오 추가',exact:true}).click();
 await expect(page.locator('#detail-title')).toHaveText('내 시나리오 1');
 await page.getByRole('button',{name:'내 시나리오 수정',exact:true}).click();
 await expect(page.getByRole('spinbutton',{name:'1학기 생활비 대출액',exact:true})).toHaveValue('125');
 await page.getByRole('button',{name:'취소',exact:true}).click();
 await page.getByRole('button',{name:'삭제',exact:true}).click();
 await expect(page.getByRole('combobox',{name:'비교할 시나리오 B',exact:true}).locator('option[value="custom-1"]')).toHaveCount(0);
});
